config/routes.rb
Rails.application.routes.draw do
	root 'schools#index'

  resources :schools do
 		resources :classrooms
 	end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	validates_presence_of :name

	belongs_to :school

	def classroom_name
		"#{name} is a cool class."
	end

	def classroom_size
		if (size >= 50)
			"Big class"
		elsif (size < 50 && size > 25)
			"Medium class"
		else (size < 30)
			"Small class"
		end
	end
end

app/models/school.rb
class School < ActiveRecord::Base
	validates_presence_of :name, :year, :mascot

	has_many :classrooms

	def school_name
		"The school name is #{name}, with a #{mascot} as the mascot"
	end

	def year_built
		school_year = year.to_i
		if (school_year > 2000)
			"New"
		elsif (school_year >= 1950 && school_year < 2000)
			"Old"
		else (school_year < 1950)
			"Old as hell"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	before_action :school
	before_action :classroom, except: [:index, :new, :create]

  def index
  	@classrooms = @school.classrooms.all.paginate(:page => params[:page], :per_page => 6)

  end

  def show
  end

  def edit
  end

  def update
  	if @classroom.update(classroom_params)
      flash[:success] = "Classroom has been updated!"
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :edit
  	end
  end

  def new
  	@classroom = @school.classrooms.new
  end

  def create
  	@classroom = @school.classrooms.new(classroom_params)
  	if @classroom.save
      flash[:success] = "Classroom has been created!"
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :new
  	end
  end

  def destroy
  	@classroom.destroy
    flash[:success] = "Classroom has been dropped"
  	redirect_to school_classrooms_path(@school)
  end

  private
  	def classroom_params
  		params.require(:classroom).permit(:name, :size)
  	end

  	def classroom
  		@classroom = @school.classrooms.find(params[:id])
  	end

  	def school
  		@school = School.find(params[:school_id])
  	end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :school, except: [:index, :new, :create]

  def index
  	@schools = School.all.paginate(:page => params[:page], :per_page => 6)

  end

  def show
  end

  def edit
  end

  def update
  	if @school.update(school_params)
  		flash[:success] = "School updated."
  		redirect_to school_path(@school)
  	else
  		render :edit
  	end
  end

  def new
    @school = School.new
  end

  def create
  	@school = School.new(school_params)
  	if @school.save
  		flash[:success] = "School created."
  		redirect_to school_path(@school)
  	else
  		render :new
  	end
  end

  def destroy
  	@school.destroy
  	flash[:success] = "School deleted"
  	redirect_to schools_path
  end

  private
  	def school_params
  		params.require(:school).permit(:name, :mascot, :year)
  	end

  	def school
  		@school = School.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/classrooms/_form.html.erb
<div class='center container'>

	<%= form_for [@school, @classroom] do |f| %>

		<%= f.label :name, class:'form-text' %>
		<%= f.text_field :name %>

		<%= f.label :size, class:'form-text' %>
		<%= f.text_field :size %>

		<%= f.submit nil, class: 'btn submit-classroom-btn green' %>

		<%= link_to 'Cancel', :back, class:'btn cancel-classroom-btn black' %>

	<% end %>

</div>

app/views/classrooms/edit.html.erb
<h1>Editing: <%= @classroom.name %></h1>

<%= render(partial: 'form') %>

app/views/classrooms/index.html.erb
<h1 id='classrooms-header'>Classrooms For: <%= @school.name %></h1>

<% if @classrooms.any? %>
  <div class='row '>
    <% @classrooms.each do |classroom| %>
      <div class="col s12 m6 l4 ">
       <div class="card red darken-3">
         <div class="card-content">
           <span class="card-title"><%= @school.classrooms.find(classroom).name %></span>
         </div>
         <div class="card-action">
           <%= link_to 'Look at Class', school_classroom_path(@school, classroom), class: 'btn' %>
         </div>
       </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class='no-classrooms-header'>No classes, please add one.</h3>
<% end %>

<div class='paginate'>
  <%= will_paginate @classrooms %>
</div>

<div class='center'>
  <%= link_to 'Add New Classes', new_school_classroom_path(@school), class:'btn new-classroom-btn green' %>
  <%= link_to 'Back to school', school_path(@school), class:'btn black back-to-school-btn' %>
</div>

app/views/classrooms/new.html.erb
<h1 id='new-classroom-header'>Creating a Class</h1>

<%= render(partial: 'form') %>

app/views/classrooms/show.html.erb
<div class='center'>

	<h1 class='show-classroom-header'>Class: <%= @classroom.name %></h1>

	<h3>Classroom Size: <%= @classroom.size %></h3>

	<%= link_to 'Edit', edit_school_classroom_path(@school, @classroom), class:'btn edit-classroom-btn orange' %>

	<%= link_to 'Delete', school_classroom_path(@school, @classroom), method: :delete, class:'btn delete-classroom-btn red' %>

	<%= link_to 'Back To Class', school_classrooms_path(@school), class:'btn back-to-classrooms-btn black' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolSpec</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3>
	<% if flash.any? %>
		<% flash.each do |key, value| %>
			<div class="flash <%= key %>">
				<%= value %>
			</div>
		<% end %>
	<% end %>
</h3>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<div class='center container'>
	<%= form_for @school do |f| %>

		<%= f.label :name, class:'form-text' %>
		<%= f.text_field :name %>

		<%= f.label :mascot, class:'form-text' %>
		<%= f.text_field :mascot %>

		<%= f.label :year, class:'form-text' %>
		<%= f.number_field :year %>

		<%= f.submit nil, class:'btn submit-school-btn green' %>

		<%= link_to 'Cancel', :back, class:'btn cancel-school-btn black' %>

	<% end %>
</div>

app/views/schools/edit.html.erb
<h1>Editing School: <%= @school.name %></h1>


<%= render(partial: 'form') %>

app/views/schools/index.html.erb
<h1 id='school-header'>Schoolio</h1>

<% if @schools.any? %>
  <div class='row container center'>
    <% @schools.each do |school| %>
      <div class="col s12 m6 l4">
       <div class="card red darken-3">
         <div class="card-content">
           <span class="card-title"><%= school.name %></span>
         </div>
         <div class="card-action">
           <%= link_to 'Check Out School', school_path(school), class: 'btn view-school-btn' %>
         </div>
       </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 id='no-school-header'>No schools, please add one.</h3>
<% end %>

<div class='paginate'>
  <%= will_paginate @schools %>
</div>

<div class='center'>
  <%= link_to 'New School', new_school_path, class:'btn new-school-btn green' %> 
</div>

app/views/schools/new.html.erb
<h1 id='new-school-header'>Creating a New School</h1>


<%= render(partial: 'form') %>

app/views/schools/show.html.erb
<div class='center'>

	<h1 class='show-school-header'>Displaying: <%= @school.name %> Home of the <%= @school.mascot %>!</h1>

	<h3 class='school-info-header'><%= @school.name %> was founded in <%= @school.year %></h3>


	<%= link_to 'Back To Schools', schools_path, class:'btn back-to-schools-btn black' %>

	<%= link_to 'Classrooms', school_classrooms_path(@school), class:'btn classrooms-btn blue' %> 
	<br />

	<%= link_to 'Edit', edit_school_path(@school), class:'btn edit-school-btn orange' %>

	<%= link_to 'Delete', school_path(@school), method: :delete, class:'btn delete-school-btn red' %>

</div>